export enum MODULES {
  Base = "Base",
  Contrato = "Contrato",
  Cargo = "Cargo",
  Contratante = "Contratante",
  Dispositivo = "Dispositivo",
  Funcionario = "Funcionario",
  Veiculo = "Veiculo",
  TipoVeiculo = "TipoVeiculo",
  Equipe = "Equipe",
  TipoEquipe = "TipoEquipe",
  Checklist = "Checklist",
  TipoChecklist = "TipoChecklist",
  PerguntaChecklist = "PerguntaChecklist",
  OpcaoResposta = "OpcaoResposta",
  Usuarios = "Usuarios",
}
